---
version: "2.1"
services:
  code-server:
    build:
      context: .
    image: self/code-server:${TAG}
    container_name: code-server
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - PROXY_DOMAIN=${PROXY}
      - DEFAULT_WORKSPACE=/workspace
    volumes:
      - /usr/local/etc/code-server:/config
      - /usr/local/lib/git:/workspace
    ports:
      - 8443:8443
    restart: unless-stopped
