---
apiVersion: v1
kind: Pod
metadata:
  name: onlyoffice
  labels:
    app: onlyoffice
spec:
  containers:
    - name: onlyoffice
      image: docker.io/onlyoffice/documentserver:latest
      ports:
        - containerPort: 80
          hostPort: 8080
        - containerPort: 443
          hostPort: 8443
      secret:
        secretName: onlyoffice-secret
      securityContext: {}
