# podman build --tag local/jenkins_controller:<date> <this_file>
FROM jenkins/jenkins:lts-jdk17
USER root:root

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt install --yes python3 python3-pip && \
    apt clean
