---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    app: jenkins-pod
spec:
  containers:
    - name: jenkins-ssh-agent
      # image: localhost/jenkins-ssh-agent:latest
      image: docker.io/jenkins/ssh-agent:latest
      env:
        - name: JENKINS_AGENT_SSH_PUBKEY
          valueFrom:
            secretKeyRef:
              name: jenkins-key
              key: ssh-pubkey
      securityContext: {}

    - name: jenkins-controller
      image: docker.io/jenkins/jenkins:latest
      ports:
        - containerPort: 8080
          hostPort: 8080
        - containerPort: 50000
          hostPort: 50000
      securityContext:
        fsGroup: 1000
      volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins_home-pvc
  volumes:
    - name: jenkins_home-pvc
      persistentVolumeClaim:
        claimName: jenkins_home
