---
# podman-compose --file <this_file> up --force-recreate --detach --build --pull
version: '3.8'

volumes:
  jenkins_home:
    name: jenkins_home

services:
  jenkins-controller:
    image: jenkins/jenkins:lts-jdk17
    privileged: true
    user: root
    container_name: jenkins-controller
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - type: volume
        source: jenkins_home
        target: /var/jenkins_home

  ssh-agent-python:
    image: localhost/ssh-agent-python:latest
    build:
      context: .
      dockerfile: ssh-agent-python.Containerfile
    privileged: true
    user: root
    container_name: ssh-agent-python
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
