---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    app: jenkins-pod
spec:
  containers:
    - name: ssh-agent-python
      # image: localhost/ssh-agent-python:latest
      image: docker.io/jenkins/inbound-agent:latest
      env:
        - name: JENKINS_SECRET
          valueFrom:
            secretKeyRef:
              name: jenkins-secret
              key: JENKINS_SECRET
      securityContext: {}

    - name: jenkins-controller
      image: localhost/jenkins-controller:latest
      ports:
        - containerPort: 8080
          hostPort: 8080
        - containerPort: 50000
          hostPort: 50000
      securityContext:
        fsGroup: 1000
      volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins_home-pvc
  volumes:
    - name: jenkins_home-pvc
      persistentVolumeClaim:
        claimName: jenkins_home
