---
# podman-compose -f <this_file.yaml> up --build --detach
version: '3.8'

services:
  jenkins_agent:
    image: local/ssh-agent-python:latest
    privileged: true
    user: root
    container_name: ssh-agent-python
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
