---
apiVersion: v1
kind: Pod
metadata:
  name: actualbudget-pod
  labels:
    app: actualbudget-pod
spec:
  containers:
    - name: actualbudget
      image: docker.io/actualbudget/actual-server:latest
      env:
        - name: NODE_EXTRA_CA_CERTS
          value: "/data/selfhost.crt"
        - name: ACTUAL_HTTPS_KEY
          value: "/data/selfhost.key"
        - name: ACTUAL_HTTPS_CERT
          value: "/data/selfhost.crt"
      ports:
        - containerPort: 5006
          hostPort: 5006
      volumeMounts:
        - mountPath: /data
          name: actualbudget_data-pvc
      securityContext: {}
      livenessProbe:
        exec:
          command:
            - node
            - scripts/health-check.js
        initialDelaySeconds: 20
        periodSeconds: 60

  volumes:
    - name: actualbudget_data-pvc
      persistentVolumeClaim:
        claimName: actualbudget_data
